export const enum TARGET_MOD_PREFIX {
	CS = 'CS',
	IS = 'IS',
	BT = 'BT',
	MA = 'MA',
	ST = 'ST',
	ES = 'ES'
}

export const TARGET_MOD_PREFIX_ARR: TARGET_MOD_PREFIX[] = [
	TARGET_MOD_PREFIX.CS,
	TARGET_MOD_PREFIX.IS,
	TARGET_MOD_PREFIX.BT,
	TARGET_MOD_PREFIX.MA,
	TARGET_MOD_PREFIX.ST,
	TARGET_MOD_PREFIX.ES
]
